### ISSUE TITLE
Values ShiftedX & Y

### ISSUE THREAD

**Issue by ghost** [Etayson/fraction-bsgs#2]
Hi Etar,
Could you help explain ShiftedX and Y values for what and it from where?
![1](https://github.com/Etayson/fraction-bsgs/assets/42763020/3b3b3d52-bf7f-4ebc-99a2-633d01337232)

receive 64 result if divisor with -dbit 6 it look like division only. if receive one result positive with distance to cal back will better we can do that ?
Thanks.

**Comment by Etayson** [comment]
'Search value' = 038c6f65d02102dd6ada8b31304eb5a0bcfe6dda9b21f7902c54e8b7fa50c2964e
And this value can lie in range 0x200000000000000 : 0x3ffffffffffffff

But we do shifting begin range to zero and range will be 0x00 : 0x1ffffffffffffff
In that case we need also substruct begin range from 'Search value' and call this value like 'Shifted value'
Shifted value = Search value - divstart range
divstart range = 0x200000000000000
Pub key of divstart range is 02f6f622083daf54800456be134d5f67d147c82642befc1ce2dc83a27078f2827c

```

038c6f65d02102dd6ada8b31304eb5a0bcfe6dda9b21f7902c54e8b7fa50c2964e 
-
02f6f622083daf54800456be134d5f67d147c82642befc1ce2dc83a27078f2827c
=
02d1071471be7d643b0e927cd37e3ada3b3187d51dff914b0c65cc3c3c56820448
```

So we search 02d1071471be7d643b0e927cd37e3ada3b3187d51dff914b0c65cc3c3c56820448
in range 0x00 : 0x1ffffffffffffff

**Comment by ghost** [comment]
Understood, thanks.
